### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by openm1nd** [PureSwift/MySQLSwift#2]
$ swift build 
Compiling Swift Module 'MySQL' (9 sources)
/home/vagrant/external/MySQL/Sources/MySQL/Row.swift:37:28: error: use of unresolved identifier 'DataFromBytePointer'
                let data = DataFromBytePointer(fieldValuePointer, length: Int(length))
                           ^~~~~~~~~~~~~~~~~~~
<unknown>:0: error: build had 1 command failures
swift-build: exit(1): ["/home/vagrant/swift-2.2-SNAPSHOT-2015-12-01-b-ubuntu14.04/usr/bin/swift-build-tool", "-f", "/home/vagrant/external/MySQL/.build/debug/MySQL.o/llbuild.yaml"]

**Comment by openm1nd** [comment]
Is it just some missing library?

**Comment by colemancda** [comment]
No. `Data` was defined as `[UInt8]`and now its a `struct` with a `var: byteValue: [UInt8]`. All you need to do is change that line of code to:

let data = Data.fromBytePointer(fieldValuePointer, length: Int(length))

**Comment by openm1nd** [comment]
Not it builds, but now I have another problem:
tmp/main-718245.o:(.text+0x19b): undefined reference to `_TMaCC5MySQL5MySQL10Connection'
/tmp/main-718245.o:(.text+0x1a3): undefined reference to`_TFCC5MySQL5MySQL10ConnectionCfT_S1_'
/tmp/main-718245.o:(.text+0x222): undefined reference to `_TIFCC5MySQL5MySQL10Connection7connectFzTGSqSS_4userGSqSS_8passwordGSqSS_12databaseNameGSqSS_4portVs6UInt326socketGSqSS_5flagsSu_T_A1_'
/tmp/main-718245.o:(.text+0x257): undefined reference to`_TIFCC5MySQL5MySQL10Connection7connectFzTGSqSS_4userGSqSS_8passwordGSqSS_12databaseNameGSqSS_4portVs6UInt326socketGSqSS_5flagsSu_T_A2_'
/tmp/main-718245.o:(.text+0x288): undefined reference to `_TIFCC5MySQL5MySQL10Connection7connectFzTGSqSS_4userGSqSS_8passwordGSqSS_12databaseNameGSqSS_4portVs6UInt326socketGSqSS_5flagsSu_T_A3_'
/tmp/main-718245.o:(.text+0x297): undefined reference to`_TIFCC5MySQL5MySQL10Connection7connectFzTGSqSS_4userGSqSS_8passwordGSqSS_12databaseNameGSqSS_4portVs6UInt326socketGSqSS_5flagsSu_T_A4_'
/tmp/main-718245.o:(.text+0x2c8): undefined reference to `_TIFCC5MySQL5MySQL10Connection7connectFzTGSqSS_4userGSqSS_8passwordGSqSS_12databaseNameGSqSS_4portVs6UInt326socketGSqSS_5flagsSu_T_A5_'
/tmp/main-718245.o:(.text+0x426): undefined reference to`_TFCC5MySQL5MySQL10Connection7connectfzTGSqSS_4userGSqSS_8passwordGSqSS_12databaseNameGSqSS_4portVs6UInt326socketGSqSS_5flagsSu_T_'
