### ISSUE TITLE
Catch block does not print error

### ISSUE THREAD

**Issue by HarshitDaftary** [PureSwift/MySQLSwift#6]
I have used following code for connecting with database, but I am facing error and the Error is not getting printed in Catch block.

```
        let user = "root"
        let databaseName = "TestDb"
        let hostname = "192.168.1.102"

        let connection = MySQL.Connection()

        do {

                try connection.connect(hostname, user: user, password: "pass123", databaseName: databaseName, port: 3306)

         }

        catch {

                print("Error while connection \(error)")
         }
```

Above code always goes in catch block and never prints the error. Can you please guide me how can I print the error so I can come to know whats wrong I am doing.

**Comment by colemancda** [comment]
This is a Swift bug [SR-175](https://bugs.swift.org/browse/SR-175)
